### PR TITLE
Make routes configurable in backoffice

### PR DESCRIPTION
**Pull request by smeeckaert**
I've added a new launcher that allows you to customize routes.

It's based on the lib_options so it supports multiple contexts.

### CODE REVIEW

**Comment by Meroje** [comment]
lib_options is not open sourced though

**Comment by smeeckaert** [comment]
Since when ? https://github.com/Foine/lib_options

**Comment by Meroje** [comment]
is it ? Couldn't find it under our NS.

**Comment by Meroje** [comment]
Sorry ¯_(ツ)_/¯, here's your thumb :+1:

**Pull request merged**
